spring:
  datasource:
    url: jdbc:h2:mem:supplier
    driver-class-name: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
